@startuml
group wp-load.php
  group wp-config.php (try to load if exists)
    group wp-settings.php
      - WPINC/load.php WPINC/default-constants.php
      - WPINC/plugin.php
      - WPINC/version.php
      - ?WP_CONTENT_DIR/advanced-cache.php
      - WPINC/compat.php
      - WPINC/class-wp-list-util.php
      - WPINC/functions.php
      - WPINC/class-wp-matchesmapregex.php
      - WPINC/class-wp.php
      - WPINC/class-wp-error.php
      - WPINC/pomo/mo.php
      - WPINC/class-phpass.php
      - WPINC/default-filters.php
      - ?WPINC/class-wp-site-query.php
      - ?WPINC/class-wp-network-query.php
      - ?WPINC/ms-blogs.php
      - ?WPINC/ms-settings.php
      - WPINC/l10n.php
      - WPINC/class-wp-locale.php
      - WPINC/class-wp-locale-switcher.php
      - WPINC/class-wp-walker.php
      - WPINC/class-wp-ajax-response.php
      - WPINC/formatting.php
      - WPINC/capabilities.php
      - WPINC/class-wp-roles.php
      - WPINC/class-wp-role.php
      - WPINC/class-wp-user.php
      - WPINC/class-wp-query.php
      - WPINC/query.php
      - WPINC/date.php
      - WPINC/theme.php
      - WPINC/class-wp-theme.php
      - WPINC/template.php
      - WPINC/user.php
      - WPINC/class-wp-user-query.php
      - WPINC/class-wp-session-tokens.php
      - WPINC/class-wp-user-meta-session-tokens.php
      - WPINC/meta.php
      - WPINC/class-wp-meta-query.php
      - WPINC/class-wp-metadata-lazyloader.php
      - WPINC/general-template.php
      - WPINC/link-template.php
      - WPINC/author-template.php
      - WPINC/post.php
      - WPINC/class-walker-page.php
      - WPINC/class-walker-page-dropdown.php
      - WPINC/class-wp-post-type.php
      - WPINC/class-wp-post.php
      - WPINC/post-template.php
      - WPINC/revision.php
      - WPINC/post-formats.php
      - WPINC/post-thumbnail-template.php
      - WPINC/category.php
      - WPINC/class-walker-category.php
      - WPINC/class-walker-category-dropdown.php
      - WPINC/category-template.php
      - WPINC/comment.php
      - WPINC/class-wp-comment.php
      - WPINC/class-wp-comment-query.php
      - WPINC/class-walker-comment.php
      - WPINC/comment-template.php
      - WPINC/rewrite.php
      - WPINC/class-wp-rewrite.php
      - WPINC/feed.php
      - WPINC/bookmark.php
      - WPINC/bookmark-template.php
      - WPINC/kses.php External library
      - WPINC/cron.php
      - WPINC/deprecated.php
      - WPINC/script-loader.php
      - WPINC/taxonomy.php
      - WPINC/class-wp-taxonomy.php
      - WPINC/class-wp-term.php
      - WPINC/class-wp-term-query.php
      - WPINC/class-wp-tax-query.php
      - WPINC/update.php
      - WPINC/canonical.php
      - WPINC/shortcodes.php
      - WPINC/embed.php
      - WPINC/class-wp-embed.php
      - WPINC/class-oembed.php
      - WPINC/class-wp-oembed-controller.php
      - WPINC/media.php
      - WPINC/http.php
      - WPINC/class-http.php
      - WPINC/class-wp-http-streams.php
      - WPINC/class-wp-http-curl.php
      - WPINC/class-wp-http-proxy.php
      - WPINC/class-wp-http-cookie.php
      - WPINC/class-wp-http-encoding.php
      - WPINC/class-wp-http-response.php
      - WPINC/class-wp-http-requests-response.php
      - WPINC/class-wp-http-requests-hooks.php
      - WPINC/widgets.php
      - WPINC/class-wp-widget.php
      - WPINC/class-wp-widget-factory.php
      - WPINC/nav-menu.php
      - WPINC/nav-menu-template.php
      - WPINC/admin-bar.php
      - WPINC/rest-api.php
      - WPINC/rest-api/class-wp-rest-server.php
      - WPINC/rest-api/class-wp-rest-response.php
      - WPINC/rest-api/class-wp-rest-request.php
      - WPINC/rest-api/endpoints/class-wp-rest-controller.php
      - WPINC/rest-api/endpoints/class-wp-rest-posts-controller.php
      - WPINC/rest-api/endpoints/class-wp-rest-attachments-controller.php
      - WPINC/rest-api/endpoints/class-wp-rest-post-types-controller.php
      - WPINC/rest-api/endpoints/class-wp-rest-post-statuses-controller.php
      - WPINC/rest-api/endpoints/class-wp-rest-revisions-controller.php
      - WPINC/rest-api/endpoints/class-wp-rest-taxonomies-controller.php
      - WPINC/rest-api/endpoints/class-wp-rest-terms-controller.php
      - WPINC/rest-api/endpoints/class-wp-rest-users-controller.php
      - WPINC/rest-api/endpoints/class-wp-rest-comments-controller.php
      - WPINC/rest-api/endpoints/class-wp-rest-settings-controller.php
      - WPINC/rest-api/fields/class-wp-rest-meta-fields.php
      - WPINC/rest-api/fields/class-wp-rest-comment-meta-fields.php
      - WPINC/rest-api/fields/class-wp-rest-post-meta-fields.php
      - WPINC/rest-api/fields/class-wp-rest-term-meta-fields.php
      - WPINC/rest-api/fields/class-wp-rest-user-meta-fields.php
      - ?WPINC/ms-functions.php
      - ?WPINC/ms-default-filters.php
      - ?WPINC/ms-deprecated.php
      - ?wp-content/mu-plugins/*
      - WPINC/vars.php (Mostly wp_is_mobile() setup and declaration)
      - ?wp-content/plugins/*|loaded_plugins
      - WPINC/pluggable.php
      - WPINC/pluggable-deprecated.php
      - WP_LANG_DIR/$locale.php
      - ?STYLESHEETPATH/functions.php
      - ?TEMPLATEPATH/functions.php
      - ?ms_site_check()
end
@enduml
